FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
# Install only production dependencies and ignore dev dependencies
RUN npm ci --omit=dev

# Copy source
COPY . .

EXPOSE 3000

CMD ["node", "server.js"]